# You are creating this instance in Virginia, Zone A (us-east-1a)
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --log-level debug --timeout 120 --workers 2 --threads 4
    expose:
      - "8000"
    volumes:
      - build-data:/app/dashboard/build
      - media_volume:/app/media
      - static_volume:/app/django-static
    networks:
      - webnet

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    env_file:
      - .env
    volumes:
      - media_volume:/app/media
      - static_volume:/app/django-static
      - build-data:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - django
    networks:
      - webnet

volumes:
  build-data:
  media_volume:
  static_volume:

networks:
  webnet:
    driver: bridge
