# Generated by Django 5.1 on 2024-11-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
