server {
    listen 80;
    server_name bioinformatica.fca.unesp.br;

    # Redireciona todo o tráfego HTTP para HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name bioinformatica.fca.unesp.br;

    client_max_body_size 500M;

    ssl_certificate /etc/letsencrypt/live/bioinformatica.fca.unesp.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bioinformatica.fca.unesp.br/privkey.pem;

    location /api/ {
        proxy_pass http://django:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /django-static/ {
        alias /app/django-static/;
    }

    location /media/ {
        alias /app/media/;
    }
}
